### ISSUE TITLE
Evaluation Form: View

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#104]
### User Story
As a challenge manager, in order to verify form details I previously created without disrupting evaluators' evaluation experience, I would like to be able to view an evaluation without being able to edit it.

**Acceptance criteria:**

- [x] A challenge manager can view an evaluation form after evaluation start date by clicking on 'edit form' from the evaluation forms list view
- [x] All form fields, except Evaluation End Date, are disabled after evaluation start date (or challenge end date)
- [x] Evaluation End Date can be edited anytime

### Definition of Done

**Doing (dev team)**
- [x] Code complete 
- [x] Code is organized appropriately
- [x] Any known trade offs are documented in the associated GH issue
- [x] Code is documented, modules, shared functions, etc.
- [x] Automated testing has been added or updated in response to changes in this PR
- [x] The feature is smoke tested to confirm it meets requirements
- [x] Database changes have been peer reviewed for index changes and performance bottlenecks
- [x] PR that changes or adds UI
  - [x] include a screenshot of the WAVE report for the altered pages
  - [x] Confirm changes were validated for mobile responsiveness
- [x] PR approved / Peer reviewed 
- [x] Security scans passed
- [x] Automate accessibility tests passed
- [x] Build process and deployment is automated and repeatable
- [ ] ~Feature toggles if appropriate~
- [x] Deploy to staging
- [x] Move card to testing column in the board
---
**Staging**
- [x] Usability testing: mobile and desktop (Tracy or Marni)
- [x] Accessibility tested (Marni)
  - [x]  Keyboard navigation
  - [x]  Focus confirmed
  - [x] Color contrast compliance
  - [x] Screen reader testing 
- [x] Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)
  - [x] Windows/Chrome
  - [x] Windows/Edge
  - [x] Mac/Chrome
  - [x] Mac/Safari
  - [x] iOS/Safari
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [x] Move to production column in the board
---
**Production**
- [ ] User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team) 
- [ ] PO / PM approved (Jarah or Renata)
- [ ] AC is met and it works as expected (Jarah or Renata)
- [ ] Move to done column in the board (Jarah or Renata)

**Comment by r-bartlett-gsa** [comment]
![Image](https://github.com/user-attachments/assets/51d57d6e-f014-485a-a9c2-ba6577c3b660)
![Image](https://github.com/user-attachments/assets/4db1fa0e-4b3a-446a-a1c9-93fad738e610)

**Comment by stepchud** [comment]
~~@stonefilipczak we need to add the automated a11y tests in order to close this out now. I merged your PRs without it already so this issue will need a new PR to address this.~~

Resolved.

**Comment by mhotch24** [comment]
@r-bartlett-gsa Card passes accessibility, usability and cross browser testing.
