### ISSUE TITLE
System Diagrams

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#110]
- [x] Create new system diagrams for SSPP:
  - [x] Network / Architectural diagram
  - [x] Data flow diagram
- [x] Write the narratives to describe the diagrams

Considerations:

- The diagrams should clearly represent ATO boundary, Cloud.gov, Login.gov
- Data flow direction
- Authentication and protocols
- See a good example in the comments
- See [historical challenge.gov diagrams](https://docs.google.com/document/d/1y1hqPxa47odnTfK7lhbeurOqIvP9QC2gBiMWebE5_AQ/edit?usp=sharing)

**Comment by r-bartlett-gsa** [comment]
Exemplary diagram:

![Image](https://github.com/user-attachments/assets/283b2e8d-2e62-409e-aff5-f6c67a8d3886)

**Comment by TCKapGrp** [comment]
Meeting with Stephen, Alejandro and Dan on Monday to discuss how to update these diagrams.  They will come to the meeting with the updates needed or questions to get answered.

**Comment by TCKapGrp** [comment]
Assigning this card to @danivovich.  Please update diagram and put location of that diagram in this card. Please update narrative.  When done, please ping @jdonis so he can do a quick review. Thank you.

**Comment by danivovich** [comment]
Working copy of the description which includes links to the diagrams https://docs.google.com/document/d/1vC7a5IkQ2ugyM0RP_Mz_GMOIY2hGUtvKOW9QCQirxhE/edit#heading=h.ovx7qnej8z7y
