### ISSUE TITLE
Continuous a11y integration: axe

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#114]
As a site engineer, in order to ensure the quality and accessibility of our code, I would like an automated accessibility tool to test all our of code.

Acceptance criteria:

- [ ] [axe-core-rspec](https://github.com/dequelabs/axe-core-gems/tree/develop/packages/axe-core-rspec) is implemented for Challenge_platform repo and runs with the other CI tests

**Comment by TCKapGrp** [comment]
Hi @stepchud , we are holding on this work for clarity from GSA on if Pa11y is a requirement as a tool.

**Comment by stepchud** [comment]
@TCKapGrp I moved this back to `doing` based on @kkrug's feedback about Axe being acceptable for use in GSA.
