### ISSUE TITLE
Challenge manager role access

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#13]
### User Story
As a user with a challenge manager role, in order to setup evaluations for the submissions of my challenges and efficiently manage the entire evaluation process, I would like to be able to access appropriate sections of the site upon login.

**Acceptance criteria:**

- [x] When a user with a challenge manager role logs in, they are sent to the Challenge Manager's dashboard on the Rails app, #53 
- [x] An appropriate utility menu is displayed for the user, https://github.com/GSA/Challenge_platform/issues/27
- [x] If any other user who does not have a challenge manager's role assigned to them tries to access challenge manager role specific features, they are redirected to their /dashboard (based on their assigned role) and an error message is displayed: "You do not have access to this section of Challenge.gov."

**Development tasks:**

- [x] #158

### Definition of Done

**Doing (dev team)**
- [x] Code complete 
- [x] Code is organized appropriately
- [x] Any known trade offs are documented in the associated GH issue
- [x] Code is documented, modules, shared functions, etc.
- [x] Automated testing has been added or updated in response to changes in this PR
- [x] The feature is smoke tested to confirm it meets requirements
- [x] Database changes have been peer reviewed for index changes and performance bottlenecks
- [ ] ~PR that changes or adds UI~
  - [ ] ~include a screenshot of the WAVE report for the altered pages~
  - [ ] ~Confirm changes were validated for mobile responsiveness~
- [x] PR approved / Peer reviewed 
- [x] Security scans passed
- [x] Automate accessibility tests passed
- [x] Build process and deployment is automated and repeatable
- [x] Feature toggles if appropriate
- [x] Deploy to staging
- [x] Move card to testing column in the board
---
**Staging**
- [x] Accessibility tested (Marni)
  - [x]  Keyboard navigation
  - [x]  Focus confirmed
  - [x] Color contrast compliance
  - [x] Screen reader testing 
- [x] Usability testing: mobile and desktop (Tracy or Marni)
- [x] Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)
  - [x] Windows/Chrome
  - [x] Windows/Edge
  - [x] Mac/Chrome
  - [x] Mac/Safari
  - [x] iOS/Safari
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [x] Move to production column in the board
---
**Production**
- [ ] User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team) 
- [x] PO / PM approved (Jarah or Renata)
- [x] AC is met and it works as expected (Jarah or Renata)
- [ ] Move to done column in the board (Jarah or Renata)

**Comment by TCKapGrp** [comment]
@mhotch24 , I was experiencing issues in Mac/Safari with keyboard testing -- specifically tabbing.  Can you check this one please?
