### ISSUE TITLE
Create a list view of EvaluationForms

### ISSUE THREAD

**Issue by stepchud** [GSA/Challenge_platform#130]
Implement a responsive list view for the `/evaluation_forms` index.

## Acceptance Criteria
- [x] `Create New Evaluation Form` button that routes to ...
- [x] New route `/evaluation_forms/new` (empty/placeholder view for now)
- [x] Empty state view with Create button and message copy (see mockups)
- [x] New helper function for Challenge Phase text that concatenates the name of the challenge with the phase "<Challenge title> <Phase number>" (this will also be used on the Create/Edit form to list phases)
- [x] Evaluation Form Card component
  - [x] Links to the Evaluation Form
  - [x] Links to the Challenge Phase
  - [ ] ~Form Status~
  - [x] Edit | ~Preview~ | Delete buttons
  - [x] Edit button links to ...
    - [x] New route `GET /evaluation_forms/:id/edit`
  - [ ] ~Preview button links to ...~
    - [ ] ~New route `GET /evaluation_forms/:id/preview`~
  - [x] Delete button links to ...
    - [x] New route `DELETE /evaluation_forms/:id`
- [x] Responsiveness on mobile and desktop
- [x] Accessible via keyboard navigation
- [x] Tested
  - [x] Expected links and text present on the card
  - [x] Accessibility test for empty state and non-empty forms list views
  - [ ] WAVE score screenshot on the PR

## Mockups
https://www.figma.com/design/VfdBFG8ShVnOStdSNYy9fR/Challenge.Gov-Component-Library?node-id=909-27901&t=eDJ6OARy6ROsTRli-1
![Image](https://github.com/user-attachments/assets/d4c5140e-edbf-4ea3-8b0d-3e1e79e6b428)
![Image](https://github.com/user-attachments/assets/cd219d0a-2c68-472f-bb85-49ab9060f2cd)

**Comment by r-bartlett-gsa** [comment]
Updated designs: ![Image](https://github.com/user-attachments/assets/7e408bb8-5d67-44d6-ae1f-2f104aaab0f1)

**Comment by TCKapGrp** [comment]
Hiya @stonefilipczak, can you help me with getting past the  "Challenge Must Exist" Error I'm getting when submitting the form?
