### ISSUE TITLE
Evaluator role access

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#16]
### User Story
As a user with an evaluator role, in order to evaluate submissions assigned to me, I would like to be able to access evaluation section of the site.

**Acceptance criteria:**
- [x] When a user with an evaluator role logs in, they are sent to the Evaluator's dashboard on the Rails app, #52 
- [x] An appropriate utility menu is displayed for the user, #27 
- [x] If any other user who does not have an evaluator's role assigned to them tries to navigate to the URL directly (access evaluator role specific features), they are redirected to their `/dashboard` (based on their assigned role) ~and an error message is displayed: "You do not have access to this section of Challenge.gov."~

**Development tasks:**

- [x] #158

### Definition of Done

**Doing (dev team)**
- [x] Code complete 
- [x] Code is organized appropriately
- [x] Any known trade offs are documented in the associated GH issue
- [x] Code is documented, modules, shared functions, etc.
- [x] Automated testing has been added or updated in response to changes in this PR
- [x] The feature is smoke tested to confirm it meets requirements
- [x] Database changes have been peer reviewed for index changes and performance bottlenecks
- [ ] ~PR that changes or adds UI~
  - [ ] ~include a screenshot of the WAVE report for the altered pages~
  - [ ] ~Confirm changes were validated for mobile responsiveness~
- [x] PR approved / Peer reviewed 
- [x] Security scans passed
- [x] Automate accessibility tests passed
- [x] Build process and deployment is automated and repeatable
- [x] Feature toggles if appropriate
- [x] Deploy to staging
- [x] Move card to testing column in the board
---
**Staging**
- [x] Usability testing: mobile and desktop (Tracy or Marni)
- [ ] ~Accessibility tested (Marni)~
  - [ ]  Keyboard navigation
  - [ ]  Focus confirmed
  - [ ] Color contrast compliance
  - [ ] Screen reader testing
- [ ] ~Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)~
  - [ ] Windows/Chrome
  - [ ] Windows/Edge
  - [ ] Mac/Chrome
  - [ ] Mac/Safari
  - [ ] iOS/Safari
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [x] Move to production column in the board
---
**Production**
- [ ] User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team) 
- [x] PO / PM approved (Jarah or Renata)
- [x] AC is met and it works as expected (Jarah or Renata)
- [ ] Move to done column in the board (Jarah or Renata)

**Comment by TCKapGrp** [comment]
@mhotch24 Can you provide @stepchud how the error should look like?

**Comment by TCKapGrp** [comment]
@stepchud, please update the dev task for the errror message.

**Comment by TCKapGrp** [comment]
@cpreisinger 

I did not get the error message per the AC.

Steps to duplicate.
1 - Log into Eval
2 - Use Solver Credentials
3 - Land on Phoenix App
4 - Paste URL: https://challenge-dev.app.cloud.gov/dashboard into browser.

You get a "logged out dashboard" page, not the error.

**Comment by stepchud** [comment]
@TCKapGrp I tested this out with a new public solver account (didn't have one yet) and instead of showing me the Logged Out Dashboard page, it redirects me to the Challenge Portal logged in as a Public Solver. This should be the correct behavior instead of showing an error message that a public solver doesn't know how to fix, they should just be redirected to the Portal (Phoenix) with access only to their public solver features (submissions etc). Let me know if you see something different.
Is it possible your login timed out while you were testing (should be 15 minutes)?

**Comment by TCKapGrp** [comment]
@stepchud  I think what you are describing is the "happy path" where a person just logs into the system and gets properly redirected.  The AC has a requirement that if you copy/paste the URL it displays an error message.  I did the above proceedure twice (log in as Eval, got directed to Phoneix, copy/paste dashboard URL)  and it landed on this page: ![Image](https://github.com/user-attachments/assets/ec4eaac4-5ffa-4608-b68a-cc03190a87bc)

**Comment by r-bartlett-gsa** [comment]
@TCKapGrp I crossed out the error message part of the 3rd criteria, and also re-tested it and it worked as @stepchud described (as expected). If you are getting a logged out screen instead of getting routed to public solver's dashboard, please try testing it in incognito and see if that resolves the issue.

@stepchud The caching issue for when trying to navigate multiple user roles we'll need to eventually resolve, and I will create a separate ticket for it.

**Comment by TCKapGrp** [comment]
Thank you @r-bartlett-gsa .  I was using the URL I thought I was supposed to for login which was incorrect.  I was using incognito mode. I've updated my notes for the correct url to use for login.  Testing with that URL, it works great!


https://gsa-tts.slack.com/archives/GTETE7W82/p1729607717227789

**Comment by TCKapGrp** [comment]
@mhotch24 , confirming that as card does not display new UI the a11y testing N/A.  cross browser testing N/A. Any user experience difficulities caused by any confusion why the /dashboard link doesn't "work" by pasting it into the browser is not affecting people with disabilities disproportionately.
