### ISSUE TITLE
Build UI - Eval Form Step 2 - Evaluation Criteria Add/Remove Criteria

### ISSUE THREAD

**Issue by stepchud** [GSA/Challenge_platform#162]
# What/Why
This task allows the user to create the basics of the criteria as well as add and remove criteria on the form. After this task is complete, valid forms can be created and published, albeit using only the numeric scoring option.

## Acceptance Criteria
- [x] Initial/empty state:
![Screenshot 2024-09-13 at 12 44 37 PM](https://github.com/user-attachments/assets/72771e2a-1a41-4cc3-8738-c2216a171efc)
- [x] Add Another Criteria Button adds a new, empty criteria to the form
- [x] Delete button removes the criteria from the form
  - [x] when the last criteria is remove the form will have one criteria in the empty/default state
- [x] Close button collapses the options to a single row view ~showing the Title~
  - [x] Expand displays the options
  ![Screenshot 2024-09-13 at 12 33 10 PM](https://github.com/user-attachments/assets/c106e16a-dc2f-4d0b-adc7-b7d19d61359c)
- [x] `Title`, `Description`, `Points`, `Scoring Type` are required
- [x] Numeric type of scoring is selected and functional
  - Rating and Binary scale are out of scope, if selected nothing happens (the form is always :numeric scoring at this point)
- [x] Criteria Points / Weight are positive integers
  - no decimal or negative numbers may be entered

_Disregard the following if this work **does not** include any UI changes_
- [x] WAVE screenshot
- [ ] Automated a11y tests (axe-rspec specs)
- [x] Keyboard accessibility (tab navigation, form interactions)
- [x] Responsiveness at desktop and mobile

**Comment by cpreisinger** [comment]
![Screenshot 2024-10-31 at 4 08 02 PM](https://github.com/user-attachments/assets/4f3b9567-675c-4cd4-b9d1-d9a6f26fe573)
