### ISSUE TITLE
Build UI - Eval Form Step 2 - Evaluation Criteria Binary Scale

### ISSUE THREAD

**Issue by stepchud** [GSA/Challenge_platform#164]
# What/Why
This task adds the ability to add binary scale options to the form.

### Figma/Mockup
![Screenshot 2024-09-13 at 1 17 10 PM](https://github.com/user-attachments/assets/b6814384-f711-49d7-a960-1a75f97e5c5f)

## Acceptance Criteria
- [x] When the user select **Binary scale**, the option is set on the criteria
- [x] Labels are required, and initially empty
  * empty label fails validation 

_Disregard the following if this work **does not** include any UI changes_
- [x] WAVE screenshot
- [ ] Automated a11y tests (axe-rspec specs)
- [x] Keyboard accessibility (tab navigation, form interactions)
- [x] Responsiveness at desktop and mobile

## Out of Scope
Tooltips #168

**Comment by cpreisinger** [comment]
![Screenshot 2024-10-31 at 4 08 02 PM](https://github.com/user-attachments/assets/73f9a23d-d7d2-4161-9bb7-dc2c4d44507d)
