### ISSUE TITLE
Build UI - Eval Form Step 2 - Evaluation Criteria Rating Scale

### ISSUE THREAD

**Issue by stepchud** [GSA/Challenge_platform#165]
# What/Why
This task adds the ability to add rating scale options to the form.

### Figma/Mockup
![Screenshot 2024-09-13 at 1 24 08 PM](https://github.com/user-attachments/assets/ff79b384-7c3b-4486-bbd9-0251914625e2)

## Acceptance Criteria
- [x] matches the mockup

_Disregard the following if this work **does not** include any UI changes_
- [x] WAVE screenshot
- [ ] Automated a11y tests (axe-rspec specs)
- [x] Keyboard accessibility (tab navigation, form interactions)
- [x] Responsiveness at desktop and mobile

## Out of Scope
Tooltips #168

**Comment by cpreisinger** [comment]
![Screenshot 2024-10-31 at 4 08 02 PM](https://github.com/user-attachments/assets/d6b651c2-76dc-4d1a-b59b-a5714bfec813)

**Comment by stepchud** [comment]
Fixed in #219
