### ISSUE TITLE
Eval Form - Save button implementation

### ISSUE THREAD

**Issue by stepchud** [GSA/Challenge_platform#167]
# What/Why
This task will enable the user to Save a valid evaluation form.
It must be completed after (is blocked by) #162, #163 

## Acceptance Criteria
- [x] Save validates all form fields
  - [x] Form start_date is automatically set to the Challenge Phase `phase.end_date`
  - [x] Form end_date must be after the Form start_date
  - [x] Form end_date is always editable
  - [x] Total of all Criteria for Weighted Scoring must add up to 100
  - [x] When the evaluation period starts, form fields are not editable (except end_date)
- [x] If the form passes validation it is persisted to the DB
- [x] If the form passes validation, the [confirmation page](https://www.figma.com/design/VfdBFG8ShVnOStdSNYy9fR/Challenge.Gov-Component-Library?node-id=1239-29446&t=UTyLsZ8gf0KP6LM4-1) is displayed to the user

_Disregard the following if this work **does not** include any UI changes_
- [x] WAVE screenshot
- [ ] Automated a11y tests (axe-rspec specs)
- [x] Keyboard accessibility (tab navigation, form interactions)
- [x] Responsiveness at desktop and mobile

**Comment by r-bartlett-gsa** [comment]
@stepchud 

Suggested rewrite of the AC:

- [x] 'Save' validates all form fields
- [x] Evaluation start date is Challenge close date
- [x] Evaluation end date is after start date
- [x] Evaluation end date is always editable
- [x] Total of all Criteria for Weighted Scoring must add up to 100
- [x] If the form passes validation a confirmation page is displayed
- [x] The form fields, expect end date, are not editable between evaluation period dates

**Comment by cpreisinger** [comment]
![Screenshot 2024-10-31 at 4 08 02 PM](https://github.com/user-attachments/assets/8ae5d95a-68cc-44fb-ad3e-ce5508435a24)

**Comment by stepchud** [comment]
Fixed in #219
