### ISSUE TITLE
SPIKE: Scanning Tools

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#18]
As a site engineer, in order to ensure the quality, security and accessibility of our code, I would like to determine which automated scanning tools will work best for our system.

Acceptance criteria:

- [x] Review and determine if any automated scanning tools are appropriate for Challange.gov repos:
  - [ ] [MegaLinter](https://megalinter.io/latest/)
  - [ ] [SonarQube](https://www.sonarsource.com/products/sonarqube/)
  - [ ] Any other tool?
- [x] If any of the tools are determined as a good fit, discuss with the PO, and create backlog items for integration / configuration of those tools

**Comment by stepchud** [comment]
@r-bartlett-gsa I think the requirements of this ticket are being met:

> As a site engineer, in order to ensure the quality, security and accessibility of our code, I would like to determine which automated scanning tools will work best for our system.

For code quality we have rubucop and CodeClimate scans on PRs. For security we have dependabot and Snyk scans. For accessibility we have the WAVE screenshots for UI PRs and the AXE rspec tests running in CI. In my opinion the current scanning more than sufficient and the other tools like MegaLinter and SonarQube offer similar functionality that will duplicate the errors and be more maintenance burden that is not providing ROI. Marking this closed now.

**Comment by r-bartlett-gsa** [comment]
Sounds good! Thank you @stepchud
