### ISSUE TITLE
Evaluation Form Validation - Part 1

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#181]
### User story
As a challenge manager, in order to ensure that a valid form is available for the evaluators to use, I would like a form to be validated for errors and valid logic before it is saved.

**Acceptance Criteria:**
- [x] When a challenge manager saves the form:
  - [x] All required fields must be provided
  - [ ] ~~The form must be assigned to a challenge / challenge phase that is not closed~~ we still need to assign a closed phase that doesn't have a form defined yet
  - [x] The form must have at least one evaluation criteria
    - [x] If weighted scale is used, then a total weight for all criteria must add up to 100
  - [x] The form is not saved if it does not pass required field validation
- [x] If the form contains missing required fields of invalid information an inline error message is displayed, and if the form is saved with any invalid information, an error message is displayed at the top of the page, #296
- [x] A challenge manager can cancel the form and the form is not saved
- [ ] ~The form is auto saved only when the form is in editing mode and all required fields are provided~

**Development tasks:**

- [x] #188
- [x] #204

### Definition of Done

**Doing (dev team)**
- [x] Code complete 
- [x] Code is organized appropriately
- [x] Any known trade offs are documented in the associated GH issue
- [x] Code is documented, modules, shared functions, etc.
- [x] Automated testing has been added or updated in response to changes in this PR
- [x] The feature is smoke tested to confirm it meets requirements
- [x] Database changes have been peer reviewed for index changes and performance bottlenecks
- [x] PR that changes or adds UI
  - [x] include a screenshot of the WAVE report for the altered pages
  - [x] Confirm changes were validated for mobile responsiveness
- [x] PR approved / Peer reviewed 
- [x] Security scans passed
- [ ] Automate accessibility tests passed
- [x] Build process and deployment is automated and repeatable
- [x] Feature toggles if appropriate
- [ ] Deploy to staging
- [x] Move card to testing column in the board
---
**Staging**
- [x] Usability testing: mobile and desktop (Tracy or Marni)
- [x] Accessibility tested (Marni)
  - [x]  Keyboard navigation
  - [x]  Focus confirmed
  - [x] Color contrast compliance
  - [x] Screen reader testing 
- [x] Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)
  - [x] Windows/Chrome
  - [x] Windows/Edge
  - [x] Mac/Chrome
  - [x] Mac/Safari
  - [x] iOS/Safari
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [x] Move to production column in the board
---
**Production**
- [ ] User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team) 
- [ ] PO / PM approved (Jarah or Renata)
- [ ] AC is met and it works as expected (Jarah or Renata)
- [ ] Move to done column in the board (Jarah or Renata)

**Comment by r-bartlett-gsa** [comment]
![Image](https://github.com/user-attachments/assets/45b5298e-c91d-401b-8ebb-80f95683e319)

---
![Image](https://github.com/user-attachments/assets/aabe0b62-f4be-46d1-bb05-7bfb220025ac)

**Comment by r-bartlett-gsa** [comment]
@stepchud Testing feedback moved from #61  

- Form validation error message is not displayed for missing form fields if any of the criteria fields are missing/incorrect, #296 
- Inline error notifications are not shown for criteria fields (the message is not the same as for the other fields and it disappears after clicking anywhere on the screen), #296 
- Cancelation modal is not displayed #283 

New feedback:
- When creating a new form, if there's any validation error when saving the form, scoring type option get removed/hidden. This does not happen if editing an existing form. See Tracy's video in the below comment. #290 
  - Additionally, if validation error is resolved, it allows to save the form with Scale Options hidden. Reopening that saved form, Scale Options display again how they were initially entered in. 
- Form title and criteria title character limit is not validated at 150 characters

![Image](https://github.com/user-attachments/assets/e3c7723e-cfe6-4944-aec7-960274413ac9)

**Comment by TCKapGrp** [comment]
Hi @r-bartlett-gsa , I know this one is sitting at AC fail right now, but ran into this during testing of other cards.  When validating the form and there are errors, the rating scale options drop off the form. Didn't want this to get lost as it doesn't seem to be an expected result. See video:  https://drive.google.com/file/d/1f6V2k5NV5pCt0pNypgl32xfiorp2sM9Q/view?usp=drive_link

**Comment by r-bartlett-gsa** [comment]
Thank you @TCKapGrp I added this finding to the list above.

**Comment by r-bartlett-gsa** [comment]
Just for the record, the following character limits should apply to form fields:

- Form title: 150
- Evaluation instructions: 3000
- Criteria title: 150
- Criteria description: 1000

(Discussed in #160)

**Comment by stepchud** [comment]
> The form is auto saved only when the form is in editing mode and all required fields are provided

@r-bartlett-gsa is this still a requirement for this Story?

**Comment by r-bartlett-gsa** [comment]
> > The form is auto saved only when the form is in editing mode and all required fields are provided
> 
> [@r-bartlett-gsa](https://github.com/r-bartlett-gsa) is this still a requirement for this Story?

@stepchud Let's leave it out for now.

**Comment by r-bartlett-gsa** [comment]
@stepchud Remaining unresolved feedback:

- Form title and criteria title character limit is not validated at 150 characters

**Comment by stepchud** [comment]
> @stepchud Remaining unresolved feedback:
> 
> * Form title and criteria title character limit is not validated at 150 characters

@r-bartlett-gsa I tested this and it looks like the maxlength on the form and criteria title is enforced on the input so the user is not able to type more than 150 characters in those fields. Can you retest this?

**Comment by r-bartlett-gsa** [comment]
@stepchud Retested and yes, that works.

**Comment by r-bartlett-gsa** [comment]
@stepchud New feedback:

- When Scale Type radio button is selected, the focus jumps to Criteria Points (skipping the fields in between) and shows validation error before anything is typed in Criteria Points Field

**Comment by stepchud** [comment]
@r-bartlett-gsa that will be resolved when we remove the html5 validation tooltips in #296 

> @stepchud New feedback:
> 
> * When Scale Type radio button is selected, the focus jumps to Criteria Points (skipping the fields in between) and shows validation error before anything is typed in Criteria Points Field

**Comment by stepchud** [comment]
#327 is merged so this can be tested again @r-bartlett-gsa
