### ISSUE TITLE
Onboard Emma

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#185]
- [x] [Onboarding spreadsheet](https://docs.google.com/spreadsheets/d/1PPd8efLQbD2-K3Tat0R77uc_djrX7eWry2j3bvr1JFk/edit?gid=544225340#gid=544225340) - Items assigned to new team member done
  - [x] [Onboarding spreadsheet](https://docs.google.com/spreadsheets/d/1PPd8efLQbD2-K3Tat0R77uc_djrX7eWry2j3bvr1JFk/edit?gid=544225340#gid=544225340) complete
- [x] Access and credentials for various accounts
- [x] Environment setup
- [x] Security training
- [x] Privileged user (?)
- [x] GSA training

**Comment by TCKapGrp** [comment]
Priv User Training completed 10/9.
