### ISSUE TITLE
New Eval Dev space in Cloud.gov

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#19]
Create a new dev space for the evaluation deployment in Cloud.gov to host the new rails app and the modified portal in the same space and allow for deployment and demonstration of the new rails application work.

**Comment by jdonis** [comment]
Space Created and roles assigned for @danivovich 

Ticket notes and screenshots 
https://docs.google.com/document/d/1a5DvV0BP67uiYuIpezoyMDpmlVarQGhP8Ea6a9eQqOM/edit?usp=sharing
