### ISSUE TITLE
Rename Submission to Evaluations & Submissions

### ISSUE THREAD

**Issue by stepchud** [GSA/Challenge_platform#192]
On the utility menu and dashboard the Submissions menu item should be renamed to Evaluations & Submissions. The subheading on the dashboard now says "Manage submissions, evaluations, and evaluators."

**Comment by r-bartlett-gsa** [comment]
@stepchud I suspect there will be additional wording changes in the near future. Perhaps we can hold off on this task and address/update wording changes in bulk.
