### ISSUE TITLE
Document process to migrate the database

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#21]
Document the steps needed to migrate the database. This is necessary because there are two applications (Phoenix & Rails) that rely on the same database and shared state across connections. Please note the deployment strategy that will happen on both apps (if needed).

Document the steps for these schema changes:
1. Adding a new table
2. Adding new columns to an existing table
3. Renaming an existing column
4. Changing an existing column's data type
5. Removing existing columns
6. Dropping existing tables

Plan for migrations needed on Phoenix production app before launch.

**Comment by stepchud** [comment]
Document created here https://github.com/GSA/Challenge_platform/wiki/How-to-migrate-the-database
