### ISSUE TITLE
Users can login via Rails app

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#22]
### User story
As a site user, in order to access the new challenge.gov Rails app (as any user), I would like to be able to login.

**Acceptance criteria:**

- [x] A user is able to login
- [x] After logging in, their session is persisted in the application

### Definition of Done

**Doing (dev team)**
- [x] Code complete 
- [x] Code is organized appropriately
- [x] Any known trade offs are documented in the associated GH issue
- [x] Code is documented, modules, shared functions, etc.
- [x] Automated testing has been added or updated in response to changes in this PR
- [x] The feature is smoke tested to confirm it meets requirements
- [ ] ~Database changes have been peer reviewed for index changes and performance bottlenecks~
- [ ] ~PR that changes or adds UI~
  - [ ] ~include a screenshot of the WAVE report for the altered pages~
  - [ ] ~Confirm changes were validated for mobile responsiveness~
- [x] PR approved / Peer reviewed 
- [x] Move card to testing column in the board
---
**Testing (dev team)**
- [x] Security scans passed
- [x] Automate accessibility tests passed
- [x] Build process and deployment is automated and repeatable
- [ ] ~Feature toggles if appropriate~
- [x] Deploy to staging

**Staging**
- [x] Accessibility tested (Marni)
  - [x]  Keyboard navigation
  - [x]  Focus confirmed
  - [x] Color contrast compliance
  - [x] Screen reader testing 
- [x] Usability testing: mobile and desktop (Tracy or Marni)
- [x] Cross browser testing (tool to be determined) (Tracy or Marni)
  - [ ]  UI rendering is performant
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [x] Move to production column in the board
---
**Production**
- [ ] User and security documentation has been reviewed for necessary updates (Renata and Michelle) 
- [x] PO / PM approved (Jarah or Renata)
- [x] AC is met and it works as expected (Jarah or Renata)
- [ ] Move to done column in the board (Jarah or Renata)

**Comment by TCKapGrp** [comment]
@cpreisinger During cross browser testing, there isn't sufficient padding under the modal.  See examples in PC Chrome and Edge.  See https://drive.google.com/file/d/1TIpdtaoMmwjWQJKC65QQ-1e-8n86G7o6/view?usp=drive_link and https://drive.google.com/file/d/1g3kkPleX0EVZSPIyDj4lEbl2Xup3n4lQ/view?usp=drive_link.

**Comment by TCKapGrp** [comment]
Tracy performed the accessibility testing including the screen reader testing using NVDA and speech viewer.  It looked clean: 


Loading complete
You must accept the U.S. Government System terms to sign into this website
clickable  navigation landmark    Challenge Gov Logo  graphic    Challenge Gov  visited  link  
My account  visited  link  
Accept and Sign-in  button  
Loading page
Welcome | Login.gov
link    Skip to main content
banner landmark    TEST SITE - Do not use real personal information (demo purposes only) - TEST SITE
Loading complete
clickable  banner landmark    Official government website  region  Here’s how you know  button  collapsed  
main landmark    Account creation tabs  navigation landmark  list  with 2 items  Sign in  visited  link    current page
Create an account  link  
Email address  edit  required  selected tracyannekelly@gmail.com
has auto complete
Password  edit  protected  required  selected •••••••••••••••
has auto complete
Show password  check box  not checked  
Sign in  button  
Loading page
Redirecting | Login.gov
https://idp.int.identitysandbox.gov/openid_connect/authorize?client_id=urn%3Agov%3Agsa%3Aopenidconne  ct.profiles%3Asp%3Asso%3Agsa%3Achallenge_gov_portal_eval_dev&response_type=code&acr_values=http%3A%2  F%2Fidmanagement.gov%2Fns%2Fassurance%2Floa%2F1&scope=openid+email&redirect_uri=https%3A%2F%2Fchalle  nge-portal-eval-dev.app.cloud.gov%2Fauth%2Fresult&state=25b7187b21f942e5cee586e6253ca121&nonce=76fd6  1f8223aed2f789db043006e979e&prompt=select_account

Challenge.Gov
banner landmark    navigation landmark    list  with 1 item  expanded  link    tracyannekelly@gmail.com  out of list
Side navigation,  navigation landmark    list  with 1 item  visited  link    Challenge.Gov  out of list
Side navigation,  navigation landmark    list  with 3 items  visited  link    Dashboard
Loading complete
