### ISSUE TITLE
Public solver role access

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#23]
### User Story
As a user with a public solver role, in order to submit my solution to a challenge, I would like to be able to access appropriate sections of the site upon login.

**Acceptance criteria:**

- [x] There are no layout or functional changes for the public solver's role:
  - [x] When a user with a public solver role logs in, they are sent to the Public Solver's dashboard on the Phoenix app
  - [x] When the user selects "Apply for this challenge" on the challenge listing page, the system assumes that the user is public solver and they are routed to an appropriate app
  - [x] The public solver only has access to the Phoenix app
- [ ] **Will revisit if this is needed. Make a ticket** ~If any other user who does not have a public solver's role assigned to them tries to access public solver role specific features, they are redirected to their /dashboard (based on their assigned role) and an error message is displayed: "You do not have access to this section of Challenge.gov."~

**Development tasks:**

- [x] #158

### Definition of Done

**Doing (dev team)**
- [x] Code complete 
- [x] Code is organized appropriately
- [x] Any known trade offs are documented in the associated GH issue
- [x] Code is documented, modules, shared functions, etc.
- [x] Automated testing has been added or updated in response to changes in this PR
- [x] The feature is smoke tested to confirm it meets requirements
- [x] Database changes have been peer reviewed for index changes and performance bottlenecks
- [ ] ~PR that changes or adds UI~
  - [ ] ~include a screenshot of the WAVE report for the altered pages~
  - [ ] ~Confirm changes were validated for mobile responsiveness~
- [x] PR approved / Peer reviewed 
- [x] Security scans passed
- [x] Automate accessibility tests passed
- [x] Build process and deployment is automated and repeatable
- [x] Feature toggles if appropriate
- [x] Deploy to staging
- [x] Move card to testing column in the board
---
**Staging**
 - [ ] ~Accessibility tested (Marni)~
 - [ ]  ~Keyboard navigation~
 - [ ]  ~Focus confirmed~
 - [ ] ~Color contrast compliance~
- [ ] ~Screen reader testing~
- [x] Usability testing: mobile and desktop (Tracy or Marni)
- [x] Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)
  - [x] Windows/Chrome
  - [x] Windows/Edge
  - [x] Mac/Chrome
  - [x] Mac/Safari
  - [x] iOS/Safari
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [x] Move to production column in the board
---
**Production**
- [ ] User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team) 
- [x] PO / PM approved (Jarah or Renata)
- [x] AC is met and it works as expected (Jarah or Renata)
- [ ] Move to done column in the board (Jarah or Renata)

**Comment by stepchud** [comment]
> If any other user who does not have a public solver's role assigned to them select "Solve Challenges" task, they are displayed an error message (along with task selection): "You do not have access to this task. Please select a different task, or contact Challenge.gov support team for assistance."

How does a public solver have the role assigned? Shouldn't any user of the system have access to be a public solver?

**Comment by r-bartlett-gsa** [comment]
> How does a public solver have the role assigned? Shouldn't any user of the system have access to be a public solver?

@stepchud Currently, if you do not have .gov or .mil email account, your role is set to public solver by default. But if you do have a .gov or .mil email account, your role is set to challenge manager, and you would have to request your role to be changed to public solver if you want to solve challenges (to avoid conflict of interest).

**Comment by TCKapGrp** [comment]
I found a small cross browser issue for PC/Edge and PC/Chrome in the login process and will update the correct card.

**Comment by TCKapGrp** [comment]
@r-bartlett-gsa all checks complete prior to move to "production" column.
