### ISSUE TITLE
Create EvaluationScore migration, model

### ISSUE THREAD

**Issue by stepchud** [GSA/Challenge_platform#230]
# What/Why
Create a design document that describes the backend storage schemas for keeping track of Evaluator scores.
- Challenge managers can override scores and we retain both scores for auditing / record keeping

# Requirements
## Create `create_evaluation_scores` migration
  ```
  create_table :evaluation_scores do
    t.references :evaluation_criterion, null: false, foreign_key: true
    t.references :user, null: false, foreign_key: true
    t.integer :score, null: false
    t.integer :score_override
    t.text :comment
    t.text :comment_override
    t.timestamps
  end
  add_index :evaluation_scores, [:evaluation_criterion_id, :user_id], unique: true
  ```

#### `score`
Evaluator original score value
- [ ] integer, not null, >= 0
Value must fall within the range of the `evaluation_criterion.scoring_type`
- [ ] `scoring_type` = "numeric"` must be in range `0...points_or_weight`, inclusive
- [ ] `scoring_type` = "binary" must be in range `option_range_start...option_range_end`, inclusive
- [ ] `scoring_type` = "rating" must be in range `option_range_start...option_range_end`, inclusive
#### `score_override`
Challenge manager optional score override
- [ ] integer, nullable
- [ ] Range validation of the value follows `score` rules
#### `comment`
 Evaluator comment for their score
- [ ] text, nullable, max length = 3000
- [ ] `validates :presence` when evaluation_form.comments_required is true
#### `comment_override`
Challenge manager optional comment override
- [ ] text, nullable, max length = 3000

### Associations
- [ ] `belongs_to :evaluation_criterion` - For determining which criterion the score is associated with through which you can find the `evaluation_form`
- [ ] `belongs_to :evaluator, class_name: 'User'` - The user with an evaluator role that the score was set by
- Other Validations
  - [ ] `evaluation_criterion_id` and `user_id` combination must be unique
  - [ ] Must be originally created by a `user` with `evaluator` role
  - [ ] `score_override` and `comment_override` can only be set by `user` with a `challenge_manager` role that is associated with the `evaluation_criterion.evaluation_form.challenge` through `ChallengeManager` model

### Create `EvaluationScore` factory
- [ ] `association :evaluation_criterion`
- [ ] `assocation :user, factory: :user do role { "evaluator" } end`
- [ ] `score { 0 } ` - Placeholder for after build validations
- [ ] `score_override { nil }`
- [ ] `comment { Faker::Lorem.sentence }`
- [ ] `comment_override { nil }`
- [ ] `trait :with_overrides`
  - [ ] `comment_override { Faker::Lorem.sentence }`
- [ ] `after(:build) do |evaluation_score, evaluator| ` - Note `evaluator` in this context is a `FactoryBot` keyword. Maybe want to use a different naming?
  - [ ] `min_score = evaluator.evaluation_criterion.option_range_start | `
  - [ ] `evaluation_score.score = Faker::Number.between(from: min_score, to: max_score)`
  - [ ] `if evaluator.instance_variable_get(:@traits)&.include?(:with_overrides)`
    - [ ] `evaluation_score.score_override = Faker::Number.between(from: min_score, to: max_score)`

### Create `EvaluationScore` spec
- [ ] Tests for validations outlined in the `fields` section above

# Notes
- Might need to make `EvaluationCriterion` with `scoring_type = numeric` properly null out `option_range_start`, `option_range_end`, and `option_labels = {}`. Either in form with hidden_inputs or in some after create/update callback

# Out of Scope
- Calculating overall scores for an evaluation form
- Audit/security log for which challenge_managers made overrides to which scores

### Figma Link

[link-to-figma](https://www.figma.com/design/VfdBFG8ShVnOStdSNYy9fR/Challenge.Gov-Component-Library)

## Acceptance Criteria
- [ ] A requirement for completion
  - [ ] Sub-requirement (optional)
  - Additional notes (optional)

_Disregard the following if this work **does not** include any UI changes_
- [ ] WAVE screenshot
- [ ] Automated a11y tests (axe-rspec specs)
- [ ] Keyboard accessibility (tab navigation, form interactions)
- [ ] Responsiveness at desktop and mobile

**Comment by stepchud** [comment]
@cpreisinger there is also an "Additional Comments" and "Revision Supporting Comments" textarea below the total score, which don't really fit on the `evaluation_scores` table

**Comment by cpreisinger** [comment]
Yeah that's an interesting wrinkle. Maybe there needs to be some kind of evaluation object.

**Comment by stepchud** [comment]
might make it easier to do the scoring average queries if we keep the sum totals in that table too, instead of having to collect all evaluation_scores per evaluator. something like ~~evaluation_summaries~~ `evaluations` table?

**Comment by stepchud** [comment]
we'll use 3000 limits for all comment fields
