### ISSUE TITLE
Evaluation Forms list view feedback

### ISSUE THREAD

**Issue by stepchud** [GSA/Challenge_platform#236]
# What/Why
Feedback on #60:
1. Add the **Evaluation Period** column to the desktop and mobile layouts as shown in the mockup.
2. Remove the **Delete** button from the list view. This is no longer part of the product requirements or design.

### Figma Link
![Image](https://github.com/user-attachments/assets/41f90c6f-cd18-45e7-af4f-a4d1105df739)
![Image](https://github.com/user-attachments/assets/ef716448-e10e-43f9-86e0-2616ff063766)

## Acceptance Criteria
- [x] column is present and displays the correct dates for each form in the list
  - [x] closing_date is required for the form
  - [x] start_date is taken from the phase like it is on the show/create view

_Disregard the following if this work **does not** include any UI changes_
- [x] WAVE screenshot
- [ ] Automated a11y tests (axe-rspec specs)
- [x] Keyboard accessibility (tab navigation, form interactions)
- [x] Responsiveness at desktop and mobile

**Comment by cpreisinger** [comment]
![Screenshot 2024-10-31 at 5 35 18 PM](https://github.com/user-attachments/assets/e2d42690-5a63-4ae8-a6e9-19315384249d)
