### ISSUE TITLE
User logout

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#24]
### User Story
As a site user, in order to ensure my information and activities are protected, I would like to logout from all site sections when I logout or timeout.

**Acceptance criteria:**

- [x] A user is logged out from all site sections (Pages, Rails and Phoenix apps) when they logout
- [x] A user is logged out from all site sections (Pages, Rails and Phoenix apps) when they timeout (15 minutes of inactivity)
  - [x] #34 

### Definition of Done

**Doing (dev team)**
- [x] Code complete 
- [x] Code is organized appropriately
- [x] Any known trade offs are documented in the associated GH issue
- [x] Code is documented, modules, shared functions, etc.
- [x] Automated testing has been added or updated in response to changes in this PR
- [x] The feature is smoke tested to confirm it meets requirements
- [ ] ~Database changes have been peer reviewed for index changes and performance bottlenecks~
- [ ] ~PR that changes or adds UI~
  - [ ] ~include a screenshot of the WAVE report for the altered pages~
  - [ ] ~Confirm changes were validated for mobile responsiveness~
- [x] PR approved / Peer reviewed
- [x] Security scans passed
- [x] Automate accessibility tests passed
- [x] Build process and deployment is automated and repeatable
- [x] Feature toggles if appropriate
- [x] Deploy to staging 
- [x] Move card to testing column in the board
---
**Staging**
- [x] Usability testing: mobile and desktop (Tracy or Marni)
- [x] Accessibility tested (Marni)
  - [x]  Keyboard navigation
  - [x]  Focus confirmed
  - [x] Color contrast compliance
  - [x] Screen reader testing 
- [x] Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)
  - [x] Windows/Chrome
  - [x] Windows/Edge
  - [x] Mac/Chrome
  - [x] Mac/Safari
  - [x] iOS/Safari
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [x] Move to production column in the board
---
**Production**
- [ ] ~User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team)~ 
- [x] PO / PM approved (Jarah or Renata)
- [x] AC is met and it works as expected (Jarah or Renata)
- [x] Move to done column in the board (Jarah or Renata)

**Comment by r-bartlett-gsa** [comment]
Related user stories:
#56 
#34 
#15 
#28

**Comment by r-bartlett-gsa** [comment]
@cpreisinger Logging out from one app does not log the user out from the other app: https://app.screencast.com/RHvrIW6lPUn5W?conversation=YVDmulma9R9TPT3HezGEiV 
This fails the the first AC for this user story.

**Comment by stepchud** [comment]
@r-bartlett-gsa which app did you logout from?

**Comment by r-bartlett-gsa** [comment]
> @r-bartlett-gsa which app did you logout from?

Logging out from either app does not log you out from the other app. I tried both.

**Comment by r-bartlett-gsa** [comment]
@stepchud and @cpreisinger Thank you for fixing this. I just tested and it works great!

**Comment by mhotch24** [comment]
@stepchud @cpreisinger When I log out on Chrome/PC as a CM and click the browser button and then click on the Challenges tile I am able to stay logged into challenge-portal-eval-dev.app.cloud.gov/challenges


https://gsa-tts.slack.com/archives/GTETE7W82/p1729531052160399

**Comment by mhotch24** [comment]
@r-bartlett-gsa testing is complete.

**Comment by r-bartlett-gsa** [comment]
@mhotch24 Was the logout also tested for accessibility?
