### ISSUE TITLE
Eval Header

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#25]
### User story
As a site user with any evaluation role, in order to build my trust using challenge.gov site, I would like to see consistent branding and styling from any page of the site.

**Acceptance criteria:**

- [x] Challenge.gov header and main nav are displayed for logged-in users using Eval capability 
- [x] When the user is logged-in, Logout button is displayed (instead of Login), #24 

### Definition of Done

**Doing (dev team)**
- [x] Code complete 
- [x] Code is organized appropriately
- [x] Any known trade offs are documented in the associated GH issue
- [x] Code is documented, modules, shared functions, etc.
- [x] Automated testing has been added or updated in response to changes in this PR
- [x] The feature is smoke tested to confirm it meets requirements
- [x] Database changes have been peer reviewed for index changes and performance bottlenecks
- [x] PR that changes or adds UI
  - [x] include a screenshot of the WAVE report for the altered pages
  - [x] Confirm changes were validated for mobile responsiveness
- [x] PR approved / Peer reviewed 
- [x] Security scans passed
- [x] Automate accessibility tests passed
- [x] Build process and deployment is automated and repeatable
- [x] Feature toggles if appropriate
- [x] Deploy to staging
- [x] Move card to testing column in the board
---
**Staging**
- [x] Accessibility tested (Marni)
  - [x]  Keyboard navigation
  - [x]  Focus confirmed
  - [x] Color contrast compliance
  - [x] Screen reader testing 
- [x] Usability testing: mobile and desktop (Tracy or Marni)
- [x] Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)
  - [x] Windows/Chrome
  - [x] Windows/Edge
  - [x] Mac/Chrome
  - [x] Mac/Safari
  - [x] iOS/Safari
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [x] Move to production column in the board
---
**Production**
- [ ] ~User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team)~ 
- [x] PO / PM approved (Jarah or Renata)
- [x] AC is met and it works as expected (Jarah or Renata)
- [x] Move to done column in the board (Jarah or Renata)

**Comment by r-bartlett-gsa** [comment]
Figma link: https://www.figma.com/design/VfdBFG8ShVnOStdSNYy9fR/Challenge.Gov-Component-Library?node-id=783-40675&t=63ttnQ9V6X1V72A5-0



![Image](https://github.com/user-attachments/assets/59477b5c-906c-4c17-bff8-4561bb9be09a)



![Image](https://github.com/user-attachments/assets/eca16819-80dc-43e6-ab06-75a42115e600)

**Comment by mhotch24** [comment]
@stonefilipczak Accessibility issue: Fail for Success Criteria 1.4.4
https://www.w3.org/WAI/WCAG21/Understanding/resize-text.html 

When user zooms to 200% the Login button disappears. This is a fail. The button needs to remain or the menu convert to hamburger/mobile menu.

**Comment by stonefilipczak** [comment]
> [@stonefilipczak](https://github.com/stonefilipczak) Accessibility issue: Fail for Success Criteria 1.4.4 https://www.w3.org/WAI/WCAG21/Understanding/resize-text.html
> 
> When user zooms to 200% the Login button disappears. This is a fail. The button needs to remain or the menu convert to hamburger/mobile menu.

@mhotch24 I can't replicate this issue on chrome - zooming to 200% causes the page to convert to hamburger layout and the login button remains visible inside the mobile menu. Could you specify what browser you're using and / or post a screen recording of the issue? Thank you!

**Comment by mhotch24** [comment]
@stonefilipczak I just retested this on https://challenge-dev.app.cloud.gov/ and it works now that the menu is added.

**Comment by mhotch24** [comment]
A11y testing complete
