### ISSUE TITLE
Eval Utility Menu

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#27]
### User story
As a challenger manager and/or a judge using eval capability, in order to efficiently navigate the site, I would like easily accessible links/buttons that take me to the main features of the eval capability.

**Acceptance criteria:**

- [x] Role-based navigation menu (utility nav menu) is displayed on each page of the Rails app
- [x] The utility nav menu reflects the same options as on the dashboard:
  - [x] #53 (with an exception of Analytics and Message Center)
  - [x] #52 

**Development tasks:**

- [x] #140 

### Definition of Done

**Doing (dev team)**
- [ ] Code complete 
- [ ] Code is organized appropriately
- [ ] Any known trade offs are documented in the associated GH issue
- [ ] Code is documented, modules, shared functions, etc.
- [ ] Automated testing has been added or updated in response to changes in this PR
- [ ] The feature is smoke tested to confirm it meets requirements
- [ ] Database changes have been peer reviewed for index changes and performance bottlenecks
- [ ] PR that changes or adds UI
  - [ ] include a screenshot of the WAVE report for the altered pages
  - [ ] Confirm changes were validated for mobile responsiveness
- [ ] PR approved / Peer reviewed 
- [ ] Security scans passed
- [ ] Automate accessibility tests passed
- [ ] Build process and deployment is automated and repeatable
- [ ] Feature toggles if appropriate
- [ ] Deploy to staging
- [ ] Move card to testing column in the board
---
**Staging**
- [x] Accessibility tested (Marni)
  - [x]  Keyboard navigation
  - [x]  Focus confirmed
  - [x] Color contrast compliance
  - [x] Screen reader testing 
- [x] Usability testing: mobile and desktop (Tracy or Marni)
- [x] Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)
  - [x] Windows/Chrome
  - [x] Windows/Edge
  - [x] Mac/Chrome
  - [x] Mac/Safari
  - [x] iOS/Safari
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [x] Move to production column in the board
---
**Production**
- [ ] ~User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team)~ 
- [x] PO / PM approved (Jarah or Renata)
- [x] AC is met and it works as expected (Jarah or Renata)
- [x] Move to done column in the board (Jarah or Renata)

**Comment by r-bartlett-gsa** [comment]
Figma link: https://www.figma.com/design/VfdBFG8ShVnOStdSNYy9fR/Challenge.Gov-Component-Library?node-id=783-40675&t=OWoWYiIk449UTAiv-0

![Image](https://github.com/user-attachments/assets/88181698-1f98-4e5b-b1f7-94ad42b806ca)



![Image](https://github.com/user-attachments/assets/a0b9d3cc-579d-481c-9d51-2249ec9e413a)

**Comment by mhotch24** [comment]
@stonefilipczak Is this card ready for testing?

**Comment by r-bartlett-gsa** [comment]
Updated mobile utility nav mockups:

Challenge manager:
![Image](https://github.com/user-attachments/assets/30527d1e-6e62-45a4-8807-75e7a5d055e5)

Evaluator:
![Image](https://github.com/user-attachments/assets/bae02699-8f43-4b36-81c0-80c4608aa74e)

**Comment by r-bartlett-gsa** [comment]
@stonefilipczak Since this one is in testing column, can you please review the DoD list and check appropriate checkboxes.

**Comment by TCKapGrp** [comment]
Tested using NVDA on PC. All nav items respond appropriately.
RailsNew
clickable  Official website of the United States government  region    button  collapsed    Here’s how you know  out of region
banner landmark    visited  link    graphic    challenge logo
Primary navigation  navigation landmark    list  with 4 items  link    Find a Challenge
link    Resources
link    Events
link    Contact  out of list
Search component  region    search landmark    Search
edit  
button    graphic    Search  out of region
button    Logout
clickable  Official website of the United States government  region    button  collapsed    Here’s how you know  out of region
Evaluator Dashboard
clickable  banner landmark    challenge logo  graphic    visited  link    challenge.gov
Primary navigation  navigation landmark  list  with 4 items  Find a Challenge  link  
Resources  link  
Events  link  
Contact  link  
Search component  region
search landmark
Search  edit  blank
Search  graphic    button  
Logout  button  
Switch Task  button
