### ISSUE TITLE
Scope Estimates

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#274]
High level estimate are needed for the following development work: 
- Login.gov IAL2 integration, see [workflow option 1](https://docs.google.com/document/d/1GQysSUVR-AFWpH8bb1tkkRTKQMh7qhaSaGzvfZNASy4/edit?usp=sharing)
  - [IAL2 Integration Guide](https://drive.google.com/file/d/1Pu8IwT6w8_aZdy5jxh6cmKRfzD9buGRS/view?usp=drive_link)
- Eval for admin and super-admin users
- Phoenix to Rails migration:
  - Challenge manager workflows (create, edit, publish challenge)
  - Public solver (submit, edit solution)
  - Admin utilities (site admin, users)

Note, user research will be conducted in the future to understand the user needs and usability of:

- Message center
- Analytics

**Comment by TCKapGrp** [comment]
@stepchud, @danivovich  and @TCKapGrp met with @r-bartlett-gsa on 11/15 to discuss the work and provide high level estimates for the top three bullet points. Renata stated that she has the info she needs for this task.
