### ISSUE TITLE
Eval Form: Cancelation modal

### ISSUE THREAD

**Issue by stepchud** [GSA/Challenge_platform#283]
# What/Why
When a user cancels the Evaluation Form form entry, they should see a modal popup that warns them their progress will be lost.

### Figma Link
![Image](https://github.com/user-attachments/assets/e258fc3d-9e6e-4639-8bd0-ea6ceab6b0df)

## Acceptance Criteria
- [x] Modal displays when the user cancels from a newly created form
- [x] Modal displays when the user cancels from an edited form

_Disregard the following if this work **does not** include any UI changes_
- [x] WAVE screenshot
- [x] Automated a11y tests (axe-rspec specs)
- [x] Keyboard accessibility (tab navigation, form interactions)
- [x] Responsiveness at desktop and mobile

## Out of Scope
Not checking "dirty" state of the form

**Comment by cpreisinger** [comment]
![Screenshot 2024-12-09 at 11 42 33 PM](https://github.com/user-attachments/assets/182398c3-93b1-464d-98ae-364cbac9f5ff)
