### ISSUE TITLE
Eval Form: Scoring options are missing after Save

### ISSUE THREAD

**Issue by stepchud** [GSA/Challenge_platform#290]
# What/Why
When validating the form and there are errors, the rating scale options drop off the form.

 _Originally posted by @TCKapGrp in [#181](https://github.com/GSA/Challenge_platform/issues/181#issuecomment-2462804284)_

## Screen-recording
https://drive.google.com/file/d/1f6V2k5NV5pCt0pNypgl32xfiorp2sM9Q/view?usp=drive_link

## Technical Notes
In order to reproduce the issue, the form must be submitted to the backend and rails responds with validation errors. It does not happen for frontend validated inputs that block form submission.

## Acceptance Criteria
- [ ] Ensure the scoring criteria options are retained after saving when the form is invalid
alidated fields.

_Disregard the following if this work **does not** include any UI changes_
- [ ] WAVE screenshot
- [ ] Automated a11y tests (axe-rspec specs)
- [ ] Keyboard accessibility (tab navigation, form interactions)
- [ ] Responsiveness at desktop and mobile

**Comment by r-bartlett-gsa** [comment]
PR: #316
