### ISSUE TITLE
Evaluation Form Validation - Part 2

### ISSUE THREAD

**Issue by stepchud** [GSA/Challenge_platform#296]
# User story
As a challenge manager, in order to ensure that a valid form is available for the evaluators to use, I would like a form to be validated for errors and valid logic before it is saved.

## Technical Notes
This will require moving away from html5 validation in the browser. The new validation will happen after the user submits the form. The controller will validate the EvalForm and EvalCriteria on the backend and return the validation errors to the frontend if it fails.

**Acceptance Criteria:**
- [x] Inline error validation is provided for missing required fields or invalid input
- [x] If there are any form validation errors upon saving the form, an error message is displayed at the top of the page and invalid fields are highlighted 
  - [x] The form is not saved until errors are resolved
- [x] If there are any validation errors for the criteria fields (for example, due to scale type change), accordions are expanded and invalid fields are highlighted
  - Weighted scoring summing up to 100 and unique criteria titles do not require inline validation errors on each criteria

### Definition of Done

**Doing (dev team)**
- [x] Code complete 
- [x] Code is organized appropriately
- [x] Any known trade offs are documented in the associated GH issue
- [x] Code is documented, modules, shared functions, etc.
- [x] Automated testing has been added or updated in response to changes in this PR
- [x] The feature is smoke tested to confirm it meets requirements
- [x] Database changes have been peer reviewed for index changes and performance bottlenecks
- [x] PR that changes or adds UI
  - [x] include a screenshot of the WAVE report for the altered pages
  - [x] Confirm changes were validated for mobile responsiveness
- [x] PR approved / Peer reviewed 
- [x] Security scans passed
- [x] Automate accessibility tests passed
- [x] Build process and deployment is automated and repeatable
- [x] Feature toggles if appropriate
- [x] Deploy to staging
- [x] Move card to testing column in the board
---
**Staging**
- [x] 12/23/24 RB note: Below items were tested with #181 
- [ ] Usability testing: mobile and desktop (Tracy or Marni)
- [ ] Accessibility tested (Marni)
  - [ ]  Keyboard navigation
  - [ ]  Focus confirmed
  - [ ] Color contrast compliance
  - [ ] Screen reader testing 
- [ ] Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)
  - [ ] Windows/Chrome
  - [ ] Windows/Edge
  - [ ] Mac/Chrome
  - [ ] Mac/Safari
  - [ ] iOS/Safari
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [x] Move to production column in the board
---
**Production**
- [ ] User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team) 
- [ ] PO / PM approved (Jarah or Renata)
- [ ] AC is met and it works as expected (Jarah or Renata)
- [ ] Move to done column in the board (Jarah or Renata)

**Comment by r-bartlett-gsa** [comment]
@stepchud / @cpreisinger  Added the AC, please verify it's inline with what we discussed.

**Comment by r-bartlett-gsa** [comment]
![Image](https://github.com/user-attachments/assets/f3cf1615-d447-4196-a36d-43539bccbe93)
