### ISSUE TITLE
Timeout Warning

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#34]
### User Story
As a site user, in order to make an informed decisions about my session on the site, I would like to be able to know when I'm about to be logged out from anywhere on the site.

**Acceptance criteria:**

- [x] The system displays a 2 minute countdown warning message before the user is logged out due to inactivity on either application, while they are on any part of the site (Pages, Rails or Phoenix)
- [x] The user can extend their session and they remain logged in on both applications
- [x] The user can end their session and they are logged out right away from both applications
- [x] If the user takes no action, the system logs them out in 2 minutes from both applications
  - [x] The user is taken to a login page with a message displaying saying that the user was logged out due to inactivity

### Definition of Done

**Doing (dev team)**
- [x] Code complete 
- [x] Code is organized appropriately
- [x] Any known trade offs are documented in the associated GH issue
- [x] Code is documented, modules, shared functions, etc.
- [x] Automated testing has been added or updated in response to changes in this PR
- [x] The feature is smoke tested to confirm it meets requirements
- [x] Database changes have been peer reviewed for index changes and performance bottlenecks
- [x] PR that changes or adds UI
  - [x] include a screenshot of the WAVE report for the altered pages
  - [x] Confirm changes were validated for mobile responsiveness
- [x] PR approved / Peer reviewed
- [x] Security scans passed
- [x] Automate accessibility tests passed
- [x] Build process and deployment is automated and repeatable
- [x] Feature toggles if appropriate
- [x] Deploy to staging 
- [x] Move card to testing column in the board
---
**Staging**
- [x] Usability testing: mobile and desktop (Tracy or Marni)
- [ ] Accessibility tested (Marni)
  - [ ]  Keyboard navigation
  - [ ]  Focus confirmed
  - [ ] Color contrast compliance
  - [ ] Screen reader testing 
- [x] Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)
  - [x] Windows/Chrome
  - [x] Windows/Edge
  - [x] Mac/Chrome
  - [x] Mac/Safari
  - [x] iOS/Safari
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [x] Move to production column in the board
---
**Production**
- [ ] ~User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team)~ 
- [x] PO / PM approved (Jarah or Renata)
- [x] AC is met and it works as expected (Jarah or Renata)
- [x] Move to done column in the board (Jarah or Renata)

**Comment by r-bartlett-gsa** [comment]
Verify if timeout is handled properly when multiple tabs are used.

**Comment by cpreisinger** [comment]
![Image](https://github.com/user-attachments/assets/2cd1b041-f4ed-410c-bcc2-4a799f4cfd63)

**Comment by TCKapGrp** [comment]
@cpreisinger , I tried yesterday 10/8 and today 10/9 to get the modal to trigger.  Did y'all turn it off?

**Comment by r-bartlett-gsa** [comment]
@TCKapGrp The timeout warning works for me as expected.

**Comment by mhotch24** [comment]
@cpreisinger UX seems off for me here. It renews the session simply when I move my mouse and not when I click the blue button. This is not the expected outcome for me and can cause confusion for users of all types. Should the message also contain notes about their current progress being autosaved?

Cannot perform A11y testing because the timeout disappears on mouse movement. Shouldn't the modal also have a "yes log me out" type option as well?

**Comment by r-bartlett-gsa** [comment]
@mhotch24 Can you please re-test this, it works for me as expected. The countdown modal remains open when I move my mouse.

Re: modal copy, for the purpose of this user story, the message is accurate, but we will want to revisit it as part of holistic testing and during fit and finish updates.

Re: logout option on the modal, I'm not sure it is needed, since the users are able to logout from the main screen.

**Comment by mhotch24** [comment]
@r-bartlett-gsa The user doesn't have to click on the button in order for the session to continue. They can click anywhere. That wasn't the expected outcome for me but if you are ok with it that way I understand. I still think the Logout option makes sense so perhaps for next version.

Accessibility testing cannot be performed for the reason stated above. When I click to launch the testing tool the session continues. I suggest making this function correctly so we can do proper A11y testing.

**Comment by r-bartlett-gsa** [comment]
@mhotch24 Can you please elaborate on "I suggest making this function correctly so we can do proper A11y testing."
In your first message you say that the modal disappears (the session renews) on mouse movement, but in the second you say that it disappears when you click anywhere on the screen. Can you please clarify.

**Comment by mhotch24** [comment]
@r-bartlett-gsa For me, the mouse doesn't need to click the blue button in order to deactivate the timeout. If we make that the function and not the mouse on-click, I will be able to do accessibility testing. So by making it only the button that triggers the event (as I was personally expecting) I will be able to do proper A11y testing.

**Comment by r-bartlett-gsa** [comment]
@stepchud To summarize the conversation above, this needs to be updated so the session renews only when the user clicks on the modal button. Currently the session renews on click anywhere on the screen and that is preventing accessibility testing.

**Comment by stepchud** [comment]
The requirements for updating the session timeout (before the warning modal appears) say that any mouse click or keypress on the page should renew the session. Are you saying that the timeout should renew differently when the modal appears than it does when the user is navigating the site normally? @r-bartlett-gsa 
I tried to locate the specific requirement for this, but I guess it is based on my interpretation of "15 minutes of inactivity" and what constitutes activity on the site. I would say any click or keypress is activity.

**Comment by stepchud** [comment]
I would argue that the intention for the modal is for users who left the browser open and started doing something else, so that they are logged out automatically. The fact that it is very easy to renew the session for users who are currently engaged with the website is a good thing, and in fact makes it more accessible than requiring a click on a specific button to renew. What do you think? @mhotch24

**Comment by r-bartlett-gsa** [comment]
@stepchud From usability perspective I agree that the user should be able to click anywhere and renew the session, but @mhotch24 was indicating that she's not able to test the modal because of how it currently works.

**Comment by stepchud** [comment]
We could change the modal to say "click anywhere or press any key to continue your session"? I think we can also disable the other event listeners and require pressing the button with a mouse or keyboard enter if that's what you want. The login flows with login.gov are already onerous and it is quite annoying as a user if I see the timeout and just miss it because I couldn't move the mouse to the button quickly enough or tab over to the correct button on the page with a few seconds remaining. I _really_ don't like that.

**Comment by r-bartlett-gsa** [comment]
@mhotch24, is there another way to test the accessibility for this without changing the requirements for how the session is renewed? Is there a setting within the accessibility testing tool that you are using that would not require to click in order to launch it, or would you be able to launch the tool before the modal appears?

**Comment by mhotch24** [comment]
@r-bartlett-gsa I can do a code review but we won't be able to do proper screenreader testing. Let me know how to proceed.

**Comment by r-bartlett-gsa** [comment]
@mhotch24 Before we decide on how to proceed, I'm still curious about the following, since most screen readers can be launched and controlled using keyboard shortcuts 

> Is there a setting within the accessibility testing tool that you are using that would not require to click in order to launch it, or would you be able to launch the tool before the modal appears?

**Comment by mhotch24** [comment]
@r-bartlett-gsa The testing process requires me to launch the testing tool. It's not that the user can't launch the screenreader. These are separate things.

**Comment by mhotch24** [comment]
@r-bartlett-gsa I did the rest of the testing as is and we can pass it.

**Comment by r-bartlett-gsa** [comment]
> [@r-bartlett-gsa](https://github.com/r-bartlett-gsa) The testing process requires me to launch the testing tool. It's not that the user can't launch the screenreader. These are separate things.

@mhotch24 My question was not about the user, it was whether **you** can launch the screenreader using keyboard shortcuts in order to test this properly. And yes, we can call this done at this time, but there might be other instances in the future that will require you to launch your testing tools without clicking, and we will definitely need to test this again before go-live, so I would recommend you to looking into this.

**Comment by mhotch24** [comment]
Yes. I'm good to test.
