### ISSUE TITLE
Create Rails SecurityLog model

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#40]
As a Rails developer, I want to have a SecurityLog data model to persist security logs.

Acceptance criteria:

- [ ] This model should mirror the existing `ChallengeGov.SecurityLogs` schema on Phoenix and not require any new migration.

**Comment by r-bartlett-gsa** [comment]
@lil-ninja Please contribute any security requirements here (and also tag me and @stepchud)

**Comment by lil-ninja** [comment]
@r-bartlett-gsa and @stepchud  Security requirements are located:  https://docs.google.com/document/d/1wct8F4au5L73ieBfRBs6foevK48jOJjCU_ukqD8a9MY/edit
