### ISSUE TITLE
CI Changes

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#47]
- [x] #166
- [x] #182
- [x] Enforce module docs with Credo
- [x] #183
- [x] Enforce security scans with build status #18 

^^^ pulled from [DoD document](https://docs.google.com/document/d/1hVR1d5naOIZp1ynDmn2k8RE6OK8oTtzsC1EPV1MHMmw/edit?usp=sharing)

**Comment by stepchud** [comment]
> Enforce module docs with Credo

Note this refers to the Phoenix app and I confirmed it is already configured to check for moduledoc with credo
