### ISSUE TITLE
Gov website header/banner

### ISSUE THREAD

**Issue by stepchud** [GSA/Challenge_platform#5]
As a developer on the challenge platform, I would like to have a common header that can be used throughout the product as needed for consistent UX.

The base layout should include the [Banner](https://designsystem.digital.gov/components/banner/) and [Identifier](https://designsystem.digital.gov/components/identifier/) components from the design system, as recommended to display the information required by law on US Gov websites.

### Definition of Done

**Doing (dev team)**
- [x] Code complete 
- [x] Code is organized appropriately
- [x] Any known trade offs are documented in the associated GH issue
- [x] Code is documented, modules, shared functions, etc.
- [x] Automated testing has been added or updated in response to changes in this PR
- [x] The feature is smoke tested to confirm it meets requirements
- [x] Database changes have been peer reviewed for index changes and performance bottlenecks
- [x] PR that changes or adds UI
  - [x] include a screenshot of the WAVE report for the altered pages
  - [x] Confirm changes were validated for mobile responsiveness
- [x] PR approved / Peer reviewed 
- [x] Move card to testing column in the board
---
**Testing (dev team)**
- [ ] Security scans passed
- [ ] Automate accessibility tests passed
- [ ] Build process and deployment is automated and repeatable
- [ ] Feature toggles if appropriate
- [ ] Deploy to staging

**Staging**
- [ ] Accessibility tested (Marni)
  - [x]  Keyboard navigation
  - [x]  Focus confirmed
  - [x] Color contrast compliance
  - [x] Screen reader testing 
- [x] Usability testing: mobile and desktop (Tracy or Marni)
- [x] Cross browser testing (tool to be determined) (Tracy or Marni)
  - [x]  UI rendering is performant
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [ ] Move to production column in the board
---
**Production**
- [ ] ~User and security documentation has been reviewed for necessary updates (Renata and Michelle)~ 
- [x] PO / PM approved (Jarah or Renata)
- [x] AC is met and it works as expected (Jarah or Renata)
- [x] Move to done column in the board (Jarah or Renata)

**Comment by mhotch24** [comment]
@stepchud is this card ready for testing? Nothing checked off. Thanks!
