### ISSUE TITLE
Implement shared session between Rails <=> Phoenix

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#56]
### User Story
As a user with access to both Phoenix (Challenge Manager) and Rails (Challenge Manager and/or Evaluator roles), I want to be able switch tasks while using the same login session.

**Acceptance criteria:**

- [x] A user will be able to switch between Rails and Phoenix apps without needing to login again 
- [ ] A user logout and the session timeout should be respected across both apps 
  - [ ] #175 - Moved to MMP
- [x] The user can access any page from either app directly without needing to login again (e.g. bookmarked pages or direct links)

### Definition of Done

**Doing (dev team)**
- [x] Code complete 
- [x] Code is organized appropriately
- [ ] Any known trade offs are documented in the associated GH issue
- [ ] Code is documented, modules, shared functions, etc.
- [x] Automated testing has been added or updated in response to changes in this PR
- [x] The feature is smoke tested to confirm it meets requirements
- [ ] ~Database changes have been peer reviewed for index changes and performance bottlenecks~
- [ ] ~PR that changes or adds UI~
  - [ ] ~include a screenshot of the WAVE report for the altered pages~
  - [ ] ~Confirm changes were validated for mobile responsiveness~
- [ ] PR approved / Peer reviewed 
- [x] Security scans passed
- [x] Automate accessibility tests passed
- [x] Build process and deployment is automated and repeatable
- [ ] ~Feature toggles if appropriate~
- [x] Deploy to staging
- [x] Move card to testing column in the board
---
**Staging**
- [ ] ~Accessibility tested (Marni)~
  - [ ]  ~Keyboard navigation~
  - [ ]  ~Focus confirmed~
  - [ ] ~Color contrast compliance~
  - [ ] ~Screen reader testing~
- [x] Usability testing: mobile and desktop (Tracy or Marni)
- [ ] ~Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)~
  - [ ] ~Windows/Chrome~
  - [ ] ~Windows/Edge~
  - [ ] ~Mac/Chrome~
  - [ ] ~Mac/Safari~
  - [ ] ~iOS/Safari~
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [x] Move to production column in the board
---
**Production**
- [ ] User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team) 
- [x] PO / PM approved (Jarah or Renata)
- [x] AC is met and it works as expected (Jarah or Renata)
- [ ] Move to done column in the board (Jarah or Renata)

**Comment by r-bartlett-gsa** [comment]
Related user stories:
#15 
#28

**Comment by TCKapGrp** [comment]
@cpreisinger , ~I'm having issues with the app respecting the login between phoenix and ruby.  Can we please review this together?~. Tried again and now it works.  Must have been an odd blip.
