### ISSUE TITLE
Evaluation Form: Create and Edit

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#61]
### User Story
As a challenge manager, in order to provide evaluators a form that they can use for scoring submissions, I would like to be able to create new, view or edit already created evaluation forms.

**Acceptance criteria:**

- [x] A challenge manager can create an evaluation form from the evaluation forms list view, and the user is taken to an evaluation form creation page
  - [x] An Evaluation Form Creation Page allows the user to setup a new evaluation form in a step-by-step process
    - [x] Enter form information
      - [x] Form title
      - [x] Assign the form to a challenge and a challenge phase, #65 
      - [x] Form instructions
   - [x] Enter evaluation criteria details, #67, #69, #68
    - [x] Setup evaluation period dates
      - [x] Evaluation start date is the end date of the challenge the evaluation form is assigned to
        - [ ] Evaluation start date makes a valid form available to the evaluators
      - [x] Evaluation end date is editable by the challenge manager at any time, even during evaluation period
        - [ ] End date disables the form from being used by evaluators
      - [x] The dates activate at midnight EST
    - [x] A challenge manager can save the form:
      - [x] All required fields must be provided
      - [ ] The form must be assigned to a challenge / challenge phase that is not closed
      - [x] The form must have at least one evaluation criteria
      - [x] The form is not saved if it does not pass required field validation
    - [x] When a valid form is saved a confirmation is displayed with an option that links to the list of evaluation forms 
    - [x] The form fields are editable by the challenge managers until Challenge/Phase end_date
      - [x] Evaluation form end date can be edited any time, even after Challenge/Phase end_date
- [x] In-line validation messages are displayed in addition to error messages that appear at the top of the form ([per USWDS guidance](https://designsystem.digital.gov/components/alert/))
- [x] A challenge manager can edit an evaluation form from the evaluation forms list view
  - [x] Editing a draft form opens a previously saved form draft and allows the user to continue manipulating form information and fields as outlined above

**Development tasks:**

- [x] #159
- [x] #160
- [x] #161
- [x] #162
- [x] #164
- [x] #165
- [x] #167

### Definition of Done

**Doing (dev team)**
- [x] Code complete 
- [x] Code is organized appropriately
- [x] Any known trade offs are documented in the associated GH issue
- [x] Code is documented, modules, shared functions, etc.
- [x] Automated testing has been added or updated in response to changes in this PR
- [x] The feature is smoke tested to confirm it meets requirements
- [x] Database changes have been peer reviewed for index changes and performance bottlenecks
- [x] PR that changes or adds UI
  - [x] include a screenshot of the WAVE report for the altered pages
  - [x] Confirm changes were validated for mobile responsiveness
- [x] PR approved / Peer reviewed 
- [x] Security scans passed
- [x] Automate accessibility tests passed
- [x] Build process and deployment is automated and repeatable
- [x] Feature toggles if appropriate
- [x] Deploy to staging
- [x] Move card to testing column in the board
---
**Staging**
- [ ] Usability testing: mobile and desktop (Tracy or Marni)
- [x] Accessibility tested (Marni)
  - [x]  Keyboard navigation
  - [x]  Focus confirmed
  - [x] Color contrast compliance
  - [x] Screen reader testing 
- [x] Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)
  - [x] Windows/Chrome
  - [x] Windows/Edge
  - [x] Mac/Chrome
  - [x] Mac/Safari
  - [x] iOS/Safari
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [x] Move to production column in the board
---
**Production**
- [ ] User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team) 
- [ ] PO / PM approved (Jarah or Renata)
- [ ] AC is met and it works as expected (Jarah or Renata)
- [ ] Move to done column in the board (Jarah or Renata)

**Comment by r-bartlett-gsa** [comment]
![Image](https://github.com/user-attachments/assets/b974fba5-008a-4289-965b-0e462732db0a)

![Image](https://github.com/user-attachments/assets/5ab1d906-7b3c-4ebc-be47-672c262f724f)

![Image](https://github.com/user-attachments/assets/456e2cda-fa81-4133-9013-b35f20b2c8b3)

**Comment by r-bartlett-gsa** [comment]
Confirmation view: 

![Image](https://github.com/user-attachments/assets/aaf0bf91-8b1c-4241-a49c-acd8cd875d14)

**Comment by stepchud** [comment]
This seems like 3 different stories that can be built separately

**Comment by r-bartlett-gsa** [comment]
> This seems like 3 different stories that can be built separately

@stepchud I'm happy to split this into three, but the way I was looking at it, is that the meat of the work is in "Create", the "Edit" is the same as create with some of the fields prefilled, and "View" is the same as edit with fields prefilled and the user cannot edit any of the fields.

**Comment by r-bartlett-gsa** [comment]
@stepchud Below is the feedback from my review. Some of that feedback can be addressed with other items that are currently in PR review, as it relates to the acceptance criteria from those user stories as well. And the design/styling feedback can be postponed until later, even though I mention it here, but I will add it to the #222  

- **Add asterisk for all required fields. Currently asterisk is missing for title, challenge, instructions, and end date**

- ~None of Scale Type options should be selected by default~, moved to #69 
- ~When another criteria is added auto-collapse the previous criteria~, moved to #67 
- ~Form validation error message is not displayed for missing form fields if any of the criteria fields are missing/incorrect~, moved to #181 
- ~Inline error notifications are not shown for criteria fields (the message is not the same as for the other fields and it disappears after clicking anywhere on the screen)~, moved to #181 
- ~Cancelation modal is not displayed~, moved to #181 

Design/styling feedback added to #222 

- Update radio button color
- Update criteria accordion color
- Update "Add Another Criteria" button color
- Step 3 vertical bar is missing
- Criteria points/weight field default text is too large and is not fully visible, perhaps should not have a default text at all
- Restyle "Remove criteria" and "Add another criteria" buttons
- Form validation error message is styled incorrectly
- Revisit all form field titles and subtitles

**Also**, please review the definition of done checklist.

**Comment by mhotch24** [comment]
@TCKapGrp @r-bartlett-gsa A11y and Cross Browser testing complete and passed.

**Comment by r-bartlett-gsa** [comment]
@stepchud One small update is needed for this story:

- Add asterisk for all required fields. Currently asterisk is missing for title, challenge, instructions and end date

**Comment by TCKapGrp** [comment]
@r-bartlett-gsa 
I just noticed you switched this to AC fail as I was doing this review.  Here is my feedback some that match yours.

User Feedback
The Criteria Title does not current appear in the collapsible accordion for the criteria as shown here in the wireframes: 
![image](https://github.com/user-attachments/assets/b499e93d-1547-4b44-93d0-4e19189f9e64)

The "e" is not capitalized in the title of the page:
![image](https://github.com/user-attachments/assets/0e41c454-e010-47ea-9164-01db85a1d0c4)

There are a few changes in titles and styles of form fields:
Instructions, Select a challenge, Build your evaluation criteria are renamed, the title for the critiera is now not in the accordian, some titles are not bolded, etc that I'm assuming are documented style changes or can be cleaned up later.

The error handling prioritizes the creation of a criteria first to remediate before entering the title (I would think error handling would start at the top and go down the form, not the middle).

There are required fields that are not designated with an asterisk  on the form field. 
Title
Select a Challenge
Instructions
Evaluation End Date

The style of the alerts do not conform to USWDS guidance
