### ISSUE TITLE
Evaluation Form: Scoring Type and Options

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#68]
### User Story

As a challenge manager, in order for the evaluator to score submissions based on evaluation criteria, I would like to setup custom scoring options for the evaluation form.

**Acceptance criteria:**

- [x] A challenge manager can select one of the following scoring field types for each criteria within the evaluation form creation workflow:
  - [x] Numerical score / points: 
    - [ ] ~If numerical score/points is selected by a challenge manager, a numerical input field will be displayed for an evaluator~
    - [x] The system will validate if the evaluator inputs a whole number
    - [x] The system will validate if the evaluator input is not greater than Criteria Points / Weight value provided by a challenge manager
  - [x] Rating scale 
    - [ ] ~~If rating scale option is selected by a challenge manager, radio buttons will be displayed for an evaluator with options defined by the challenge manager~~ not included in this story
    - [x] A challenge manager can create as many radio button options as needed by indicating the range from 0 or 1 to n
      - [x] A challenge manager is required to create at least two rating scale options
    - [x] Once radio button options range is provided, an appropriate number of fields is displayed for the challenge manager to provide labels for each
  - [x] Binary scale
    - [ ] ~~If binary scale option is selected, two radio buttons will be displayed for an evaluator with options defined by a challenge manager~~ not included in this story
    - [x] A challenge manager can provide labels for 0 and 1 radio button options 
- [ ] ~~Criteria score is calculated based on evaluator inputs and selections and predefined formula, #71~~ not included here

**Development tasks:**

- [ ] TBD

### Definition of Done

**Doing (dev team)**
- [x] Code complete 
- [x] Code is organized appropriately
- [x] Any known trade offs are documented in the associated GH issue
- [x] Code is documented, modules, shared functions, etc.
- [x] Automated testing has been added or updated in response to changes in this PR
- [x] The feature is smoke tested to confirm it meets requirements
- [x] Database changes have been peer reviewed for index changes and performance bottlenecks
- [x] PR that changes or adds UI
  - [x] include a screenshot of the WAVE report for the altered pages
  - [x] Confirm changes were validated for mobile responsiveness
- [x] PR approved / Peer reviewed 
- [x] Security scans passed
- [ ] Automate accessibility tests passed
- [x] Build process and deployment is automated and repeatable
- [x] Feature toggles if appropriate
- [ ] ~Deploy to staging~
- [x] Move card to testing column in the board
---
**Staging**
- [x] Usability testing: mobile and desktop (Tracy or Marni)
- [x] Accessibility tested (Marni)
  - [x]  Keyboard navigation
  - [x]  Focus confirmed
  - [x] Color contrast compliance
  - [x] Screen reader testing 
- [x] Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)
  - [x] Windows/Chrome
  - [x] Windows/Edge
  - [x] Mac/Chrome
  - [x] Mac/Safari
  - [x] iOS/Safari
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [x] Move to production column in the board
---
**Production**
- [ ] User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team) 
- [ ] PO / PM approved (Jarah or Renata)
- [ ] AC is met and it works as expected (Jarah or Renata)
- [ ] Move to done column in the board (Jarah or Renata)

**Comment by r-bartlett-gsa** [comment]
![Image](https://github.com/user-attachments/assets/70bde1a4-f2c9-4e7e-984d-475696215ff1)

![Image](https://github.com/user-attachments/assets/bc3576c1-c5dc-471e-b26b-fac9b4fc9742)

**Comment by mhotch24** [comment]
@stepchud 

**Feature Specific A11y Issues:**
- Color contrast error: Update color of order label from:   <label class="font-sans-lg text-bold text-base-light">  to class="font-sans-lg text-bold text-base">![Image](https://github.com/user-attachments/assets/680e9e69-82f0-4b86-9877-436412765049)

**Cross Browser Issue:**
- iOS: Rating Scale and Binary scale options: Need space between label and input.![Image](https://github.com/user-attachments/assets/c1187a76-d736-45d2-b9ea-ab0b133f79b1)

**Comment by stepchud** [comment]
@mhotch24 the a11y issue has been resolved with the last deploy

**Comment by mhotch24** [comment]
@r-bartlett-gsa usability and accessibility testing complete.
