### ISSUE TITLE
Evaluation Form: Scale Type

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#69]
### User story

As a challenge manager, in order to create fair and accurate scoring form, I would like to have an option to either apply weights to criteria scores or to use point scale.

**Acceptance criteria:**

- [x] A challenge manager can indicate if they want to use Point Scale or Weighted Scale for their evaluation form
- [x] When "weighted scale" option is selected:
  - [x] Criteria Points / Weight field value is used as a weight value for the criteria (#71 )
  - [x] When a challenge manager saves the form, the system validates if inputted weights for all criteria add up to 100%
    - [x] If a total weight for all criteria is not 100%, a form an error message is displayed
- [x] When "point scale" option is selected:
  - [x] Criteria Points / Weight field value is used to indicate the max score value for the criteria (#71 )
  - [x] Criteria point values for all criteria can add up to any value

**Development tasks:**

- [ ] Task 1
- [ ] Task 2

### Definition of Done

**Doing (dev team)**
- [x] Code complete 
- [x] Code is organized appropriately
- [x] Any known trade offs are documented in the associated GH issue
- [x] Code is documented, modules, shared functions, etc.
- [x] Automated testing has been added or updated in response to changes in this PR
- [x] The feature is smoke tested to confirm it meets requirements
- [x] Database changes have been peer reviewed for index changes and performance bottlenecks
- [x] PR that changes or adds UI
  - [x] include a screenshot of the WAVE report for the altered pages
  - [x] Confirm changes were validated for mobile responsiveness
- [x] PR approved / Peer reviewed 
- [x] Security scans passed
- [x] Automate accessibility tests passed
- [x] Build process and deployment is automated and repeatable
- [x] Feature toggles if appropriate
- [ ] ~Deploy to staging~
- [x] Move card to testing column in the board
---
**Staging**
- [ ] Usability testing: mobile and desktop (Tracy or Marni)
- [x] Accessibility tested (Marni)
  - [x]  Keyboard navigation
  - [x]  Focus confirmed
  - [x] Color contrast compliance
  - [x] Screen reader testing 
- [x] Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)
  - [x] Windows/Chrome
  - [x] Windows/Edge
  - [x] Mac/Chrome
  - [x] Mac/Safari
  - [x] iOS/Safari
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [x] Move to production column in the board
---
**Production**
- [ ] User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team) 
- [ ] PO / PM approved (Jarah or Renata)
- [ ] AC is met and it works as expected (Jarah or Renata)
- [ ] Move to done column in the board (Jarah or Renata)

**Comment by r-bartlett-gsa** [comment]
![Image](https://github.com/user-attachments/assets/70bde1a4-f2c9-4e7e-984d-475696215ff1)

**Comment by r-bartlett-gsa** [comment]
Moving user feedback from #61 to this appropriate user story:

- None of Scale Type options should be selected by default

**Comment by mhotch24** [comment]
@r-bartlett-gsa @TCKapGrp 
A11y and Cross Browser testing completed and passed.

**Comment by TCKapGrp** [comment]
@r-bartlett-gsa 

QA Feedback:
1 - You can type a very large number into the criteria points per the AC but if you only see the first four characters.  If a person does a copy and paste a few times or some other error in typing, there is no way to validate the data.


2 - I typed in a VERY long string of numbers: 192222900000000000000222222020202020202020202020200202020202020200202020202020

and when saving got this error:

![Image](https://github.com/user-attachments/assets/410ff29f-6f45-4ecb-8c6f-a1a022a5a8d3)


when I changed it to "20"  no error was recorded.

**Comment by r-bartlett-gsa** [comment]
@stepchud Please address the following feedback:

- [x] None of Scale Type options should be selected by default
- [x] Limit criteria points / weight field input to 4 characters / digits => moved to #275
