### ISSUE TITLE
Add Brakeman and Code Climate

### ISSUE THREAD

**Issue by stepchud** [GSA/Challenge_platform#7]
As a DevSecOps developer, I want to ensure that my code meets high quality standards and each build passes an automatic security analysis check.

Code Climate/Brakeman are the preferred tools for Ruby [Code security analysis](https://handbook.tts.gsa.gov/launching-software/security/#recommendations-by-language).

Documentation on Brakeman can be [found here](https://docs.codeclimate.com/docs/brakeman) and at the [Brakeman project repo](https://github.com/presidentbeef/brakeman).

**Comment by r-bartlett-gsa** [comment]
@stepchud Snyk is used quite often across TTS, https://github.com/snyk, and we will be adding it to the other two repos. Should we configure it for this repo as well?

https://github.com/GSA/Challenge_gov/issues/1356
https://github.com/GSA/challenges-and-prizes/issues/1952
