### ISSUE TITLE
Login.gov sandbox environment

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#8]
As a site engineer, in order to ensure proper testing and QA of user authentication features, I need a login.gov sandbox.

Acceptance criteria:

- [x] Create a new sandbox environment on login.gov for the Rails app to connect with for testing and QA

**Comment by stepchud** [comment]
<img width="633" alt="Screenshot 2024-06-27 at 7 27 16 PM" src="https://github.com/GSA/Challenge_platform/assets/148475/ee06f6e4-314f-4e68-95f8-c14184e70614">
